# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd177f2ab6edc335a621d14ff10b541932d8e3bd6130f53cd928bd8fd9d614cd780b55776f1e28990bd3fcf8c113a5ec090b6d3d43f63aaa66d8e4ff492445bc

test:
  secret_key_base: 154bb20d63aadcf646f90f964dca088bec96d6e326b5953c740cf4dc062dfe3da46604e48f6a6b1a1ebf6498795ea0807cafe2ab81cfebd04d5407f14f37c394

# Do not keep production secrets in the repository,
# instead read values from the environment.
development:
  secret_key_base: dd177f2ab6edc335a621d14ff10b541932d8e3bd6130f53cd928bd8fd9d614cd780b55776f1e28990bd3fcf8c113a5ec090b6d3d43f63aaa66d8e4ff492445bc
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

production:
  secret_key_base: 154bb20d63aadcf646f90f964dca088bec96d6e326b5953c740cf4dc062dfe3da46604e48f6a6b1a1ebf6498795ea0807cafe2ab81cfebd04d5407f14f37c394
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

